name: locoo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  faker: ^2.0.0
  file_picker: ^4.6.1
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3

  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.4
  cloud_firestore: ^3.4.0
  flutter_firebase_chat_core: ^1.6.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  mime: ^1.0.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  meta: ^1.7.0


    


  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  flutter_remix: ^0.0.3
  customizable_space_bar: ^0.2.0
  firebase_core: ^1.20.0

dev_dependencies:
  dart_code_metrics: ^4.15.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/