name: nochba
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.7.0"

dependencies:
  flutter:
    sdk: flutter

  feedback: ^2.5.0

  cupertino_icons: ^1.0.5
  faker: ^2.0.0
  # file_picker: ^5.0.1'''
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  firebase_storage: ^11.0.1
  contained_tab_bar_view: ^0.8.0
  geolocator: ^9.0.2
  url_launcher: 6.1.7
  package_info_plus: ^3.0.2
  # flutter_chat_types: ^3.4.3
  # flutter_chat_ui: ^1.6.4
  cloud_firestore: ^4.0.1
  # flutter_firebase_chat_core: pod repo update^1.6.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  textfield_tags: ^2.0.2
  mime: ^1.0.2
  shimmer: ^2.0.0
  # open_file: ^3.2.1
  path_provider: ^2.0.11
  meta: ^1.7.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  flutter_remix: ^0.0.3
  expandable_page_view: ^1.0.17
  json_theme: ^4.0.0+8
  animated_segmented_tab_control: ^1.0.1
  syncfusion_flutter_datepicker: ^20.2.45
  dotted_line: ^3.1.0
  # confetti: ^0.7.0
  lottie: ^1.4.2
  image_editor_plus: ^0.1.5
  safe_device: ^1.1.2
  # open_file: ^2.1.1
  photo_view: ^0.14.0
  visibility_detector: ^0.3.3
  # flutter_link_previewer: ^3.0.1
  flutter_parsed_text: ^2.2.1
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  linkify: ^4.1.0
  flutter_linkify: ^5.0.2
  flutter_awesome_select: ^6.5.0
  material_tag_editor: ^0.1.2
  firebase_app_check: ^0.1.1
  syncfusion_flutter_sliders: ^20.2.50
  get_time_ago: ^1.1.6
  timeago_flutter: ^1.2.0
  cloud_functions: ^4.0.6
  mobile_scanner: ^2.1.0
  firebase_crashlytics: ^3.0.8
  firebase_performance: ^0.9.0
  typesense: ^0.3.0
  firebase_messaging: ^14.2.1
  geoflutterfire2: ^2.3.14
  qr_flutter: ^4.0.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.17
  algolia: ^1.1.1
  device_info_plus: ^8.0.0
  http_parser: ^4.0.2
  flutter_dotenv: ^5.0.2
  shake: ^2.2.0
  pinch_zoom: ^1.0.0

dev_dependencies:
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons: "^0.11.0"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#  flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon_512x.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/appainter_theme.json
    - assets/chat_ui/
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        #import font 200
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
