// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcjlkWrsS8qT3e1Af3uGAz502mHHvvjE',
    appId: '1:799212549268:web:3e1a2b805133d7142ff081',
    messagingSenderId: '799212549268',
    projectId: 'nochba-dev',
    authDomain: 'nochba-dev.firebaseapp.com',
    databaseURL: 'https://nochba-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nochba-dev.appspot.com',
    measurementId: 'G-EPK19PRBVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LO0ep7beTQJCRVCSv8XI7kGfSzD_8PA',
    appId: '1:799212549268:android:76bbdf0aedd4d0fa2ff081',
    messagingSenderId: '799212549268',
    projectId: 'nochba-dev',
    databaseURL: 'https://nochba-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nochba-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDknVAkdOHsseHaZTF2pvWqYCnDXs93BJ0',
    appId: '1:799212549268:ios:7ba8ce1ee3578fd32ff081',
    messagingSenderId: '799212549268',
    projectId: 'nochba-dev',
    databaseURL: 'https://nochba-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nochba-dev.appspot.com',
    iosClientId: '799212549268-8vdlp51ealp8jh3i2j5op604ifgatpbh.apps.googleusercontent.com',
    iosBundleId: 'com.nochba.nochba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDknVAkdOHsseHaZTF2pvWqYCnDXs93BJ0',
    appId: '1:799212549268:ios:7ba8ce1ee3578fd32ff081',
    messagingSenderId: '799212549268',
    projectId: 'nochba-dev',
    databaseURL: 'https://nochba-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nochba-dev.appspot.com',
    iosClientId: '799212549268-8vdlp51ealp8jh3i2j5op604ifgatpbh.apps.googleusercontent.com',
    iosBundleId: 'com.nochba.nochba',
  );
}
