default_platform(:android)

desc "Build"
lane :build do
  gradle(task: "clean assembleRelease")
  gradle(
     task: "assemble",
     flavor: "demo",
     build_type: "release"
   )
end


platform :android do
  desc "Deploy to firebase"
  lane :deploy do
    begin
      firebase_app_distribution(
        groups: "alpha",
        release_notes: "Bug fixes and performance improvements",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        firebase_cli_path: "usr/local/bin/firebase",
        firebase_cli_token: "${{secrets.FIREBASE_TOKEN}}",
        app: "${{secrets.FIREBASE_APP_ID_ANDROID}}",
      )
    end
  end

  desc "Increment build number"
  lane :IncrementBuildNumber do

    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close

  end

  #desc "Increment version code"
  #lane :increment_vc do
  #  increment_version_code( gradle_file_path: "./app/build.gradle" )
  #end
end