name: CI
on:
  push:
    branches:
      - main
jobs:

  print_working_directory:
    name: Print Working Directory
    runs-on: ubuntu-latest
    steps:
      - run: echo "The current working directory is $(pwd)"
      - run: ls
      
  print_current_working_directory:
    name: Print Current Working Directory
    runs-on: ubuntu-latest
    steps:
      - run: cd android
      - run: echo "The current working directory is $(pwd)"






