name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Fastlane
        uses: fastlane/setup-fastlane@v2
      - name: Deploy to Firebase
        run: fastlane android deploy_to_firebase






