
' https://github.com/rubiconba/fastlane-plugin-flutter-version-manager
' https://www.runway.team/blog/how-to-set-up-a-ci-cd-pipeline-for-your-ios-app-fastlane-github-actions

' https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch:~:text=workflow_dispatch%3A%0A%20%20%20%20inputs,environment%0A%20%20%20%20%20%20%20%20required%3A%20true
@startuml


:Github Push;
:Github Action starts the line: distributeFirebase;
:the
:then incireases the build number;
:upload it to firebase app dispo;
end



:Local Build;
:enter the version number;
:you can enter manuly the version number;
:the build number increases;
:upload to playstore;
:upload to firebase app dispo;


@enduml