name: Flutter Build APK

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - '.github/workflows/flutter_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    # - name: Run tests
    #   run: flutter test

    - name: Build APK with obfuscation
      run: flutter build apk --release --obfuscate --split-debug-info=${{ github.event.repository.name }}/split-debug-info
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
